version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=restaurant_reservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./Infrastructure/Persistence/StartupScript.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    environment:
      - ConnectionStrings__Default=User ID=postgres;Password=mysecretpassword;Host=postgres-db;Port=5432;Database=restaurant_reservation;
    ports:
      - "5000:443"
      - "5001:80"
    depends_on:
      - postgres-db